server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 15
    registry-fetch-interval-seconds: 10
