server:
  port: 10010
spring:
  application:
    name: ywz-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix大
    socket-timeout-millis: 60000 #socket超时
  prefix: /api
  routes:
    item-service: /item/**
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000