server:
  port: 10010
spring:
  application:
    name: ywz-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix大
    socket-timeout-millis: 60000 #socket超时
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
  add-host-header: true #携带地址信息
  sensitive-headers: #覆盖敏感头信息
ribbon:
  ConnectTimeout: 10000 #通讯超时时间
  ReadTimeout: 10000 #获取连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ywz:
  jwt:
    pubKeyPath: G:\\tmp\\rsa\\rsa.pub #公钥地址
    cookieName: YWZ_TOKEN #cookie名称
  filter:
    allowPaths:
    # - 开头的路径表示是一个集合  list
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item