server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.100.216.155:33306/ywz?characterEncoding=utf-8&serverTimezone = UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.100.216.155
    #配置redis连接池
    timeout:

  rabbitmq:
    host: 47.100.216.155
    username: ywz
    password: ywz
    virtual-host: /ywz
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.ywz.user.pojo

#AccessKey ID LTAI4Fk3KLicoVDPJmx5h4p5
#AccessKeySecret XAeSL8dN3V9ngCE8X2GEnLko6AK4bU