server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 47.100.216.155
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
    instance:
      lease-renwal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 15
ywz:
  jwt:
    pubKeyPath: G:\\tmp\\rsa\\rsa.pub #公钥地址
    cookieName: YWZ_TOKEN #cookie名称