server:
  port: 8084

spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    username: ywz
    password: ywz
    host: 47.100.216.155
    virtual-host: /ywz
    template:
      exchange: YWZ.ITEM.EXCHANGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5

