server:
  port: 10086
spring:
  application:
    name: ywz-resgistry
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
